In [3]:
import pandas as pd
df = pd.read_csv("CustomerData.csv")
df

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,Female,Toronto,52000.0,5,45.5,Yes,10-01-2025
1,C002,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025
2,C003,29,Female,Brampton,55000.0,6,61.2,Yes,20-01-2025
3,C004,42,Male,Mississauga,82000.0,12,95,Yes,01-02-2025
4,C005,31,Female,Toronto,NaN,4,38.5,No,05-02-2025
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,08-02-2025
6,C007,150,Male,Brampton,59000.0,5,49,No,10-02-2025
7,C008,27,Male,Toronto,47000.0,3,35.25,No,12-02-2025
8,C009,36,Male,Toronto,71000.0,10,88.4,Yes,15-02-2025
9,C010,29,Female,Brampton,54000.0,6,NaN,Yes,18-02-2025
10,C011,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025
11,C012,24,Female,Toronto,45000.0,2,29.99,No,20-02-2025

In [4]:
#Cleaning the Column Names as having extra space at the end
df.columns = df.columns.str.strip()

In [5]:
#How many rows and columns are in the dataset?
df.shape

(12, 9)

In [6]:
#Which columns are available, and what data type does each contain?
df.columns #To list down all the columns
#df.info() # To display the info of the dataframe

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Income', 'Visits', 'Avg_Spend',
       'Purchased', 'Signup_Date'],
      dtype='object')

In [7]:
#Display only Customer_ID, Age, City, and Purchased.
df[["Customer_ID","Age","City","Purchased"]]

   Customer_ID  Age         City Purchased
0         C001   25     Toronto        Yes
1         C002   34     Toronto         No
2         C003   29    Brampton        Yes
3         C004   42  Mississauga       Yes
4         C005   31     Toronto         No
5         C006   31      Toronto       Yes
6         C007  150     Brampton        No
7         C008   27      Toronto        No
8         C009   36      Toronto       Yes
9        C010    29     Brampton       Yes
10       C011    34      Toronto        No
11        C012   24     Toronto         No

In [8]:
#Which customers are from Toronto?
df[df["City"] == "Toronto"]

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,08-02-2025
7,C008,27,Male,Toronto,47000.0,3,35.25,No,12-02-2025
8,C009,36,Male,Toronto,71000.0,10,88.4,Yes,15-02-2025
10,C011,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025

In [9]:
#Which customers visited more than 6 times?
df[df["Visits"] > 6]

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
1,C002,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025
3,C004,42,Male,Mississauga,82000.0,12,95,Yes,01-02-2025
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,08-02-2025
8,C009,36,Male,Toronto,71000.0,10,88.4,Yes,15-02-2025
10,C011,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025

In [10]:
#Which customers are from Toronto and purchased?
df[(df["City"] == "Toronto") & (df["Purchased"] == "Yes")]

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,08-02-2025
8,C009,36,Male,Toronto,71000.0,10,88.4,Yes,15-02-2025

In [11]:
#Which customers have income above 60,000 or more than 8 visits?
df["Income"] = pd.to_numeric(df["Income"])
df[(df["Income"] > 60000 ) | (df["Visits"]> 8)]

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
1,C002,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025
3,C004,42,Male,Mississauga,82000.0,12,95,Yes,01-02-2025
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,08-02-2025
8,C009,36,Male,Toronto,71000.0,10,88.4,Yes,15-02-2025
10,C011,34,Male,Toronto,68000.0,8,72.3,No,15-01-2025

In [12]:
#Which customer information do we need to calculate our purchase-rate KPI and identify potential high-value customers?
#Purchase Rate KPI
purchase_rate = (df["Purchased"] == "Yes").mean()
print(f"Purchase rate: {purchase_rate}")

#High-Value Customers

Purchase rate: 0.5

In [12]:
##Part 2 - Data Wrangling

# 2 How would you handle the missing Income
# value? Explain your choice. Don't automatically delete it.
# 3 How would you standardize the Gender values
# so that F, female, and Female are consistent? Think mapping/replacement.
# 4 Are there duplicate customer records? Identify
# and handle them appropriately. Check duplicated().
# 5 Which columns have incorrect or inappropriate
# data types? Inspect dtypes.
# 6 Convert Signup_Date into a proper datetime
# format. Think pd.to_datetime().
# 7 Customer C007 has an age of 150. What would
# you do with this value?
# Investigate before removing. Is every
# outlier necessarily bad?

In [15]:
# Which columns contain missing values, and how
# many are missing in each? isnull() / sum().

df.isnull().sum()

Customer_ID    0
Age            0
Gender         0
City           0
Income         1
Visits         0
Avg_Spend      1
Purchased      0
Signup_Date    0
dtype: int64